CREATE TABLE BANK_BRANCH
(BRANCH_ID CHAR(4) PRIMARY KEY,
BANK_CODE CHAR(3),
BRANCH_STREET CHAR(20),
BRANCH_CITY CHAR(15),
BRANCH_STATE CHAR(2),
BRANCH_ZIP CHAR(5),
FOREIGN KEY (BANK_CODE) REFERENCES BANK (BANK_CODE));


INSERT INTO BANK_BRANCH
VALUES
('1000','1','111 Ashton','Grove','FL','33321');

INSERT INTO BANK_BRANCH
VALUES
('2000','2','222 Oak','Los Angeles','CA','22022');

INSERT INTO BANK_BRANCH
VALUES
('3000','3','333 Bluesky','Baltimore','MD','12345');