CREATE TABLE BANK
(BANK_CODE CHAR(3) PRIMARY KEY,
BANK_STREET CHAR(20),
BANK_CITY CHAR(15),
BANK_STATE CHAR(2),
BANK_ZIP CHAR(5));


INSERT INTO BANK
VALUES
('1','123 Money','Grove','FL','33321');

INSERT INTO BANK
VALUES
('2','456 Rich','Los Angeles','CA','22022');

INSERT INTO BANK
VALUES
('3','789 Green','Baltimore','MD','12345');